title: Dhani Baharzah
description: Long Form Jekyll theme built with SASS / COMPASS / SUSY

url: http://github.com/dhanibaharzah
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 5

navigation:
  - title: Home
    url: /index.html
  - title: About
    url: /about
  - title: Contact
    url: /contact

social:
  github: dhanibaharzah
  twitter: dhanibaharzah
  facebook: dhanibaharzah
  email: dhanibaharzah@gmail.com

google_analytics: "UA-58263416-1"
